plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.shortestpath'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

// 통합 테스트 소스 설정
sourceSets {
	integrationTest {
		java.srcDir 'src/integrationTest/java'
		resources.srcDir 'src/integrationTest/resources'
		compileClasspath += sourceSets.main.output + sourceSets.test.output
        runtimeClasspath += sourceSets.main.output + sourceSets.test.output
	}
}

configurations {
    integrationTestImplementation.extendsFrom testImplementation
    integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
}

repositories {
	maven {
		url "https://repo.osgeo.org/repository/release"
	}
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation group: 'org.hibernate.orm', name: 'hibernate-spatial', version: '6.6.13.Final'
	// implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	implementation 'com.mysql:mysql-connector-j'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	// testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	implementation group:'org.geotools', name:'gt-main', version: '33.0'
	implementation group:'org.geotools', name:'gt-referencing', version: '33.0'
	implementation group:'org.geotools', name:'gt-shapefile', version: '33.0'
}


tasks.register('integrationTest', Test) {
	description = '통합 테스트 실행'
	group = 'verification'

	// 통합 테스트 소스 설정

	// 통합 테스트 클래스가 컴파일된 위치 설정
	testClassesDirs = sourceSets.integrationTest.output.classesDirs
	// 테스트에 필요한 컴파일된 클래스들 위치 설정
	classpath = sourceSets.integrationTest.runtimeClasspath

	mustRunAfter tasks.test

	useJUnitPlatform()
}

tasks.named('processIntegrationTestResources') {
    // 중복 파일이 있어도 오류 발생하지 않도록 설정
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.check {
    dependsOn tasks.integrationTest
}

tasks.named('test') {
	useJUnitPlatform()
}